CREATE TABLE IF NOT EXISTS roles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type       VARCHAR(255),
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255) NOT NULL UNIQUE,
    username   VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    identity   UUID         NOT NULL UNIQUE,
    role_id    BIGINT UNIQUE REFERENCES roles (id),
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS files (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) UNIQUE,
    size          BIGINT,
    mime_type     VARCHAR(255),
    uploaded_by   VARCHAR(255),
    upload_status SMALLINT CHECK (upload_status >= 0 AND upload_status <= 3),
    visibility    VARCHAR(255) NOT NULL DEFAULT 'PRIVATE' CHECK (visibility IN ('PRIVATE', 'PUBLIC')),
    share_token   UUID UNIQUE,
    created_at    TIMESTAMPTZ,
    updated_at    TIMESTAMPTZ
);
