CREATE TABLE IF NOT EXISTS shared_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    file_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_file_id FOREIGN KEY (file_id) REFERENCES files (id),
    CONSTRAINT uq_user_file UNIQUE (user_id, file_id)
)