spring.application.name=boxshare
server.address=0.0.0.0

app.cors.allowed-origins=http://localhost:5173

spring.config.import=optional:classpath:secrets.properties,optional:file:/resources/secrets.properties

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true